server:
  port: 8080
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8777/eureka/
zuul:
  routes:
    user:
      service-id: user
      prefix: /user/**
spring:
  application:
    name: gateway
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

ribbon:
  ReadTimeout: 180000
  ConnectTimeout: 180000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
